//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPLOM_DASHI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Kontrol_PitaniaEntities1 : DbContext
    {
        public Kontrol_PitaniaEntities1()
            : base("name=Kontrol_PitaniaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Авторизация> Авторизация { get; set; }
        public virtual DbSet<Группа> Группа { get; set; }
        public virtual DbSet<Завтрак> Завтрак { get; set; }
        public virtual DbSet<Обед> Обед { get; set; }
        public virtual DbSet<Регистрация> Регистрация { get; set; }
        public virtual DbSet<Ужин> Ужин { get; set; }
        public virtual DbSet<Воспитатели> Воспитатели { get; set; }
        public virtual DbSet<Ребенок> Ребенок { get; set; }
    }
}
