//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPLOM_DASHI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Обед
    {
        public int Id { get; set; }
        public string Первое { get; set; }
        public string Второе { get; set; }
        public string Напиток { get; set; }
        public string Pitanie { get; set; }
    }
}
