//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIPLOM_DASHI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ужин
    {
        public int Id { get; set; }
        public string Йогурт { get; set; }
        public string Запеканка { get; set; }
        public string Молоко { get; set; }
        public string Pitanie { get; set; }
    }
}
